// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// csqrt
NumericVector csqrt(NumericVector x);
RcppExport SEXP _rbclust_csqrt(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(csqrt(x));
    return rcpp_result_gen;
END_RCPP
}
// llikef_rbclust_c
double llikef_rbclust_c(List model, int n, DataFrame long_df, NumericMatrix xmat_df);
RcppExport SEXP _rbclust_llikef_rbclust_c(SEXP modelSEXP, SEXP nSEXP, SEXP long_dfSEXP, SEXP xmat_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type long_df(long_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xmat_df(xmat_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(llikef_rbclust_c(model, n, long_df, xmat_df));
    return rcpp_result_gen;
END_RCPP
}
// grad_llikef_rbclust_c
NumericVector grad_llikef_rbclust_c(List model, int n, DataFrame long_df, NumericMatrix xmat_df);
RcppExport SEXP _rbclust_grad_llikef_rbclust_c(SEXP modelSEXP, SEXP nSEXP, SEXP long_dfSEXP, SEXP xmat_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type long_df(long_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xmat_df(xmat_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_llikef_rbclust_c(model, n, long_df, xmat_df));
    return rcpp_result_gen;
END_RCPP
}
// llikef_complete_rbclust_c
double llikef_complete_rbclust_c(List model, int n, DataFrame long_df, NumericMatrix xmat_df, NumericMatrix zmat);
RcppExport SEXP _rbclust_llikef_complete_rbclust_c(SEXP modelSEXP, SEXP nSEXP, SEXP long_dfSEXP, SEXP xmat_dfSEXP, SEXP zmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type long_df(long_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xmat_df(xmat_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zmat(zmatSEXP);
    rcpp_result_gen = Rcpp::wrap(llikef_complete_rbclust_c(model, n, long_df, xmat_df, zmat));
    return rcpp_result_gen;
END_RCPP
}
// grad_llikef_complete_rbclust_c
NumericVector grad_llikef_complete_rbclust_c(List model, int n, DataFrame long_df, NumericMatrix xmat_df, NumericMatrix zmat);
RcppExport SEXP _rbclust_grad_llikef_complete_rbclust_c(SEXP modelSEXP, SEXP nSEXP, SEXP long_dfSEXP, SEXP xmat_dfSEXP, SEXP zmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type long_df(long_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xmat_df(xmat_dfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type zmat(zmatSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_llikef_complete_rbclust_c(model, n, long_df, xmat_df, zmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rbclust_csqrt", (DL_FUNC) &_rbclust_csqrt, 1},
    {"_rbclust_llikef_rbclust_c", (DL_FUNC) &_rbclust_llikef_rbclust_c, 4},
    {"_rbclust_grad_llikef_rbclust_c", (DL_FUNC) &_rbclust_grad_llikef_rbclust_c, 4},
    {"_rbclust_llikef_complete_rbclust_c", (DL_FUNC) &_rbclust_llikef_complete_rbclust_c, 5},
    {"_rbclust_grad_llikef_complete_rbclust_c", (DL_FUNC) &_rbclust_grad_llikef_complete_rbclust_c, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rbclust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
