# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Take the square root of a number
#'
#' @param x A number.
#' @return sqrt(x)
#' @export
csqrt <- function(x) {
    .Call(`_rbclust_csqrt`, x)
}

#' C++ version of log L of row clustering for binary data
#' @export
llikef_rbclust_c <- function(model, n, long_df, xmat_df) {
    .Call(`_rbclust_llikef_rbclust_c`, model, n, long_df, xmat_df)
}

#' C++ version of the gradient of log L for
#' row clustering for binary data
#' @export
grad_llikef_rbclust_c <- function(model, n, long_df, xmat_df) {
    .Call(`_rbclust_grad_llikef_rbclust_c`, model, n, long_df, xmat_df)
}

#' C++ version of the complete data log L for
#' row clustering for binary data
#' @export
llikef_complete_rbclust_c <- function(model, n, long_df, xmat_df, zmat) {
    .Call(`_rbclust_llikef_complete_rbclust_c`, model, n, long_df, xmat_df, zmat)
}

#' C++ version of the gradient of the complete data log L
#' @export
grad_llikef_complete_rbclust_c <- function(model, n, long_df, xmat_df, zmat) {
    .Call(`_rbclust_grad_llikef_complete_rbclust_c`, model, n, long_df, xmat_df, zmat)
}

